### ISSUE TITLE
Analysis process remains running forever?

### ISSUE THREAD

**Issue by Seriousness** [andersfischernielsen/Traktor-Transition-Finder#11] opened 2015-11-13 17:11 UTC
I just wondered how long the import of a collection might take. Downloaded the windows version, started and now he's loading the nml for like 6 hours, Ram is full (System process takes 3-4GB / a Traktor exe has like 2GB), hdd is running full, Cpu quite low. Can't see a process bar or log... should I keep it running or is this a bug? The animated window still moves...

**Comment by Marak** [comment] 2015-11-13 18:14
Seems like a bug. Should be very fast.

Could you confirm which version of Traktor you are running?

Also, how large is your collection file? We've seen some issues with importing large collections from certain versions of Traktor.

**Comment by Seriousness** [comment] 2015-11-14 11:30
Traktor 2.9.0 / collection.nml about 27,6 MB (24k Tracks)

**Comment by Marak** [comment] 2015-11-14 15:28
@Seriousness -

I think we might have some issues with really large collection files.

Would you mind trying again with a smaller collection? If we can confirm a smaller collection works on your setup it will confirm here that the issue is with very large collections.

**Comment by Seriousness** [comment] 2015-11-14 18:45
Jup it works then... have a small collection with 30 songs... doing fine

**Comment by Marak** [comment] 2015-11-15 18:43
@andersfischernielsen -

Do you have any insight as to why this is happening?

I'm thinking this might be related to #9, if not just a general need for optimization for larger collections.

Is there any way to perform a lazy initialization of the collection with a percentage complete indicator? I have a feeling loading a huge collection at once into the graph might be problematic. The task might need to be broken down into incremental pieces and joined later.

Really, I'm just making an educated guess. I'm not familiar enough with F# to know exactly what's going on.

**Comment by andersfischernielsen** [comment] 2015-11-16 10:33
There's a memory issue with collections with several thousand songs. The app simply eats all available memory, until it runs out and throws an exception. 
I'm currently working on it in the bugfix branch: d439b84050f9a4c0633f6d88243a5136314300a2

**Comment by andersfischernielsen** [comment] 2015-11-16 11:46
Same as: #9

**Comment by Seriousness** [comment] 2015-11-16 22:26
Thanks for the quick take on this, just downloaded the new version and still... full ram (up to 6GB) and endless cpu calculation... running for an hour now, it would be pretty neat to see some kind of process to understand if the program is running or freaking out..

Again, thanks for your help! I really like the effort you put into this piece.

**Comment by Marak** [comment] 2015-11-16 22:31
@andersfischernielsen -

Do you have a large collection file to test with?

It would be beneficial if you could replicate the issue locally.

**Comment by andersfischernielsen** [comment] 2015-11-17 10:18
I fixed it locally, apparently my test collection wasn't big enough (10.000 analysed songs). :) 
I'll look into it ASAP.

**Comment by Marak** [comment] 2015-11-17 15:04
@andersfischernielsen -

Have you put a version number anywhere in the app?

It might be a good idea to start versioning the app ( with an about dialogue ) to help triage incoming support issues. Without that, we can't be sure which version of the app users are testing.

**Comment by andersfischernielsen** [comment] 2015-11-18 08:56
@Seriousness I know it's a lot to ask, but could you email me your collection for testing? I promise I won't steal any songs. It's purely for bug fixing purposes.
My email is andersfischern@me.com

**Comment by Seriousness** [comment] 2015-11-18 15:42
done.

**Comment by andersfischernielsen** [comment] 2015-11-18 17:58
Should be fixed in https://github.com/andersfischernielsen/TraktorAutoNextSong/tree/1.1.1. :)

**Closed as completed by andersfischernielsen** 2015-11-18 17:58 UTC
Labels: bug

**Comment by andersfischernielsen** [comment] 2015-11-18 18:04
It does take a while to parse the collection, though. But the app shouldn't fail now. 
On my Retina MacBook Pro (10 threads running while parsing) it takes about 5 min. to parse a 29 MB collection. 
I've added an issue about implementing a progress bar while parsing the collection. I'll get to it when I have the time. :)

**Comment by andersfischernielsen** [comment] 2015-11-18 18:08
<img width="734" alt="screen shot 2015-11-18 at 19 06 23" src="https://cloud.githubusercontent.com/assets/5990738/11249542/c201d024-8e27-11e5-8438-a34981dc3e0f.png">
Running with a 29MB collection.

**Comment by Seriousness** [comment] 2015-11-18 22:26
I'll wait for the progress bar then, had it running for like an hour...
